[package]
name = "file-compressor"
version = "1.0.0"
edition = "2021"
authors = ["Ramkumar kushwah <kushwahramkumr20003@gmail.com>"]

[dependencies]
flate2 = "1.0"
clap = { version = "3.0", features = ["derive"] }
colored = "2.0"
indicatif = "0.17"
